spring:
  redis:
    host: 49.234.10.152
    password: redis
    database: 0 # default set to 0
    port: 6379 # default set to 6379
    lettuce:
      pool:
        max-active: 8 # Maximum number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
        max-idle: 8 # Maximum number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
        max-wait: -1
  datasource:
    url: jdbc:mysql:///springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: stein
    password: njl283036
    jpa:
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
    thymeleaf:
      cache: false