spring:
  task:
    execution:
      pool:
        queue-capacity: 20
        max-size: 10
        keep-alive: 60s
        allow-core-thread-timeout: false
        core-size: 2
      shutdown:
        await-termination: true
        await-termination-period: 30s
      thread-name-prefix: async-thread-

