spring:
  datasource:
    druid:
      url: jdbc:mysql:///springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: stein
      password: njl283036
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
      stat-view-servlet:
        # 是否开启状态监视，默认关闭
        enabled: true
        # 监视统计页面的访问规则
        url-pattern: /druid/*
        # 是否允许清空统计数据
        reset-enable: true
        # 监控管理用户密码
        login-password: stein283036
        # 监控管理用户名称
        login-username: stein
      filters: stat, wall
      initial-size: 10
      max-active: 16
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true